import Lloyd from '../../img/lloydNew.png';

export const eventData = [
	[
		'C. Dixon Osburn',
		'Executive Director of the Center for Justice and Accountability',
		'January 23, 2019 | 6:00pm - 7:30pm | Bay View Room, Eshelman Hall, UC Berkeley',
		'How can one NGO take on the world’s war criminals? Come listen to how San Francisco based Center for Justice and Accountability has been leading the charge for the past twenty years.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Julie Bloom',
		'Deputy Editor on the New York Times National Desk',
		'February 4, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'In the first half of the twentieth century, the average New York Times editor might never see California, the average New York Times reader might not have either. Much has changed since then. The Times now has more than two dozen journalists based up and down the state and more readers in the state than anywhere else in the country, including New York. Ms. Bloom will talk about the evolution of how The Times has covered California over the years, the major themes and issues its focusing on in the year ahead and what challenges The Times and other national news organizations face in trying to cover such a diverse and complex place as California.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Kate Wagner',
		'Creator of McMansion Hell',
		'February 5, 2019 | 6:00pm - 7:30pm | 210 Wurster Hall, UC Berkeley',
		'What is a McMansion? Where do they come from? What can we divine about architecture and culture from McMansions? Is the McMansion a specific type of vernacular architecture, or is it an aesthetic concept or idea? In this lecture, Kate Wagner, creator of the viral blog McMansion Hell, will illuminate why the McMansion is so ubiquitous, and how its existence is innately tied to American culture and policy.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Mandy Aftel',
		'Founder of Aftelier Perfumes',
		'February 11, 2019 | 6:00pm - 7:30pm | 125 Cheit Hall, UC Berkeley',
		'Perfumer and author Mandy Aftel’s Archive of Curious Scents shares the glorious history of natural aromatics — part of the extraordinary lineage of scent that reaches back to the beginnings of human culture and is entwined with the earliest history of medicine, cuisine, sexuality, adornment, and worship. She will walk you through some of the exhibits, show you a 400-year-old book of secrets, tell you where ambergris really comes from, and share several examples of scents that have been used in people’s daily lives in almost every culture for centuries, and are in danger of disappearing.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Lloyd B. Minor',
		'Dean of Stanford’s Medical School',
		'February 12, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'How are medical schools adapting to today’s greatest challenges? Join the Dean of Stanford University School of Medicine, Lloyd B. Minor M.D., for a discussion on the ways in which medical education is changing and responding to unique social demands. Dean Minor will specifically discuss the challenges in biomedical discovery and the vital importance of diversity in science . . .',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Andrew Chau',
		'Co-Founder of Boba Guys',
		'Febryart 14, 2019 | 6:00pm - 7:30pm | Anna Head Alumnae Hall, UC Berkeley',
		'A Valentine’s Day conversation with Andrew Chau, one of the co-founders of Boba Guys Inc. Will cover entrepreneurship, fighting for representation, and the beverage business. Disclaimer: there will be lots of ball puns.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Sonja Lyubomirsky',
		'Psychology Professor and Author of the How of Happiness',
		'February 20, 2019 | 6:00pm - 7:30pm | 230 Cheit Hall, UC Berkeley',
		'Happiness not only feels good; it is good. Happy people have more stable marriages, superior health, and higher incomes. Fortunately, experiments have shown that people can intentionally increase their happiness. In this presentation, I will describe brand new research on the “how” of happiness—that is, when and why such practices as gratitude or kindness work “best” and how small and simple activities can transform people into happier and more flourishing individuals.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Natalie Coughlin',
		'12-Time Olympic Swimming Medalist',
		'March 4, 2019 | 6:00pm - 7:30pm | Alumni House Toll Room, UC Berkeley',
		'How are Olympians made, really? We welcome back Natalie Coughlin, one of the most successful swimmers of our time, to her academic and athletic alma mater, UC Berkeley. In her talk, Natalie will reflect on her experiences as a student athlete at Cal and as an Olympic swimmer for the USA, from the triumphant moments to more challenging times. She will specifically discuss her time at Cal, her experience at the Olympics, and the ways in which her pursuit of non-sports endeavors also fits into her life.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Danielle Sered',
		'Executive Director of Common Justice',
		'March 12, 2019 | 6:00pm - 7:30pm | 180 Tan Kah Kee Hall, UC Berkeley',
		'We will never end mass incarceration without taking on the question of violence, and we will never end violence without reducing our failed reliance on prisons. Danielle Sered will discuss strategies for addressing violence that are survivor-centered, accountability-based, safety-driven, and racially equitable. She will draw from her organization Common Justice’s experience using restorative justice to address serious harm as an alternative to incarceration.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Yaron Brook',
		'Chairman of the Ayn Rand Institute',
		'March 14, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'What role does self-interest play in capitalism? What is the morality of this self-interest? In this talk, Yaron Brook delves into the morality of finance, free markets, savings, insurance and using debt to fund consumption.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Megan Grassell',
		'Founder of Yellowberry',
		'March 21, 2019 | 6:00pm - 7:30pm | 7 Evans Hall, UC Berkeley',
		'At age 17, how would you go about starting a business, much less turning it into a multi-million dollar company? The Forum invites Megan Grassell, CEO of the incredibly successful undergarment and clothing site Yellowberry, armed with the mission to “Take Girls Seriously” and create age-appropriate and empowering garments for young girls. In her talk, Megan will detail the trials and tribulations that come along with entrepreneurship as a young woman, coupled with advice about navigating this sector. She will provide an in-depth look into her personal story, as well as what lies ahead for herself and her company.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Solitary Confinement: Restorative or Ruthless',
		'Event: Debate',
		'April 4, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'The implementation of criminal justice is oft-discussed, resulting in a spectrum of views. This spectrum ranges in ideology from those who believe in prison serving a rehabilitative purpose to those who believe in a more punitive system. One particularly controversial practice, solitary confinement, consists of isolating an inmate from all human interactions, typically for 22-23 hours at a time, as a form of discipline. While some believe that this practice ought to be stopped completely, others believe that solitary confinement, if limited in use and reformed to serve a purpose in the Criminal Justice System, may have its merits. This debate will explore whether solitary confinement should continue to be employed as a practice in America’s incarceration facilities, or should instead be ridden of entirely in America’s Criminal Justice System.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Joe Deloss',
		'Owner of Hot Chicken Takeover',
		'April 10, 2019 | 6:00pm - 7:30pm | 7 Evans Hall, UC Berkeley',
		'Joe DeLoss is the founder of Hot Chicken Takeover, a Nashville-style hot chicken restaurant based in Columbus, Ohio. Joe’s not a chef, and he didn’t intend to be a restaurateur; Joe is an entrepreneur passionate about human resources and the impact it can have on someone’s life. His company, Hot Chicken Takeover, provides employment to nearly 150 men and women, almost 70% of whom have been previously impacted by incarceration or a criminal record.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
		'He will share how this strategy, identified as Fair Chance employment, is their core competitive advantage. In a job category wrought with volatility and turnover, HCT’s approach is yielding uncommon results – profitable for both employee and employer. In this keynote, Joe will debunk the myths associated with their Fair Chance employment approach and offer practical strategies for engaging diverse, entry-level workforces.',
	],
	[
		'Yoon Choi',
		'Chief Executive Officer of CollegeSpring',
		'April 15, 2019 | 6:00pm - 7:30pm | 126 Barrows Hall, UC Berkeley',
		'The use of the SAT in college admissions has sparked debate and controversy since its inception in 1926. Over the past century, the test itself has faced criticism of racial bias, while the rise of the lucrative test preparation industry has led many to question its reliability as a measure of pure academic merit. Dr. Choi’s talk gives a brief history of the test, an overview of current debates about its role in college access, and presents a path forward in which the test can be used as a tool for opportunity rather than as a barrier to college admission.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Digital Privacy Panel',
		'Speakers: Cindy Cohn, Meegan Brooks, Vijaya Kaza',
		'April 23, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'With Facebook’s most recent scandal and subsequent congressional hearing, internet users were exposed to the reality that corporations have more access to personal information than ever before. In the age of social media, the question still remains as to whether people have a reasonable expectation of privacy and the extent to which companies can control or protect private information. This panel will discuss the implications of social media technology on current extensions and limits to personal privacy.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Jill Tarter',
		'Astronomer and Pioneer for the Search for Extraterrestrial Intelligence (SETI)',
		'September 16, 2019 | 6:00pm - 7:30pm | 125 Morrison Hall, UC Berkeley',
		'Arthur C. Clarke’s third law states that “any sufficiently advanced technology is indistinguishable from magic.” Since 1960, SETI (Search for ExtraTerrestrial Intelligence) researchers have been searching for that ‘magic’ in the form of radio, and now optical, electromagnetic signals. These searches need to continue and grow utilizing the exponentially increasing capabilities of computing, but within the SETI field, we’ve always reserved the right to get smarter. In 2014, Karl Schroeder (Canadian futurist and science fiction author) suggested a variant of the Third Law; Any sufficiently advanced technology is indistinguishable from Nature. What opportunities does this increased scope of the Third Law offer to our own 21 st century search for life beyond Earth? As we design and implement the next generations of ground and space-based observatories, some of whose primary goals are the imaging of exoplanets and the spectroscopic analysis of their atmospheres, we should consider how we might distinguish between the byproducts of microbes and mathematicians. We are vigorously discussing/debating the right instruments to develop and fly to find biosignatures – how can we find the technosignatures of the mathematicians?',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
		'Jill Tarter is an astronomer and pioneer in the Search for Extraterrestrial Intelligence (SETI), and the co-founder and retired director of the SETI Institute. She has spent the majority of her professional career attempting to answer the age-old question, “Are we alone?” by searching for evidence of technological civilizations beyond Earth. She served as Project Scientist for NASA’s SETI program, the High Resolution Microwave Survey and has conducted numerous observational programs at radio observatories worldwide. She was named one of the Time 100 Most Influential People in the World in 2004, and one of the Time 25 in Space in 2012, received a TED prize in 2009, two public service awards from NASA, multiple awards for communicating science to the public, and has been honored as a woman in technology. She served as President of the California Academy of Sciences in 2015-16. In 2018 she was recognized with the Maria Mitchell Women in Science Award and the Sir Arthur Clarke Innovator’s Award. Since the termination of funding for NASA’s SETI program in 1993, she has served in a leadership role to design and build the Allen Telescope Array and to secure private funding for SETI. Dr. Tarter was also the primary inspiration for Ellie Arroway, the protagonist in the Carl Sagan’s 1985 novel Contact, and played by Jodie Foster in the 1997 movie rendition of the book.',
	],
	[
		'Gene Luen Yang',
		'Author of American Born Chinese',
		'September 19, 2019 | 6:00pm - 7:30pm | 230 Cheit Hall, UC Berkeley',
		'Asians and Asian-Americans are often portrayed as upholding some or all of the stereotypes formed against them, such as being exotic, rich, smart, and/or wimpy with glasses. These are not true, of course – they are stereotypes after all. Come join us in hearing how Gene Luen Yang combats these and other similar negative representation and, instead, promote cultural awareness as an Asian-American cartoonist.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
	],
	[
		'Travis Rosbach',
		'Co-Founder of Hydroflask',
		'September 24, 2019 | 6:00pm - 7:30pm | N270 Chou Hall, UC Berkeley',
		'Today, the Hydro Flask is one of the most used water bottles around the world, with its application of vacuum technology to an everyday, durable, and visually appealing product. During his talk, Travis will walk through his experience with the company and provide his insights for young entrepreneurs.',
		Lloyd,
		'/facebook',
		'https://calendar.google.com/event?action=TEMPLATE&tmeid=MnFtbWF2dWRuMDA2N3VvMmtncHN0Y2xoM20gbHM5OGJuMml0MGFqZWxxbThkdjdubm42ZTBAZw&tmsrc=ls98bn2it0ajelqm8dv7nnn6e0%40group.calendar.google.com',
		'Hydro Flask, a maker of double-wall vacuum insulated stainless steel water bottles, was founded in 2009 by Travis Rosbach and Cindy Morse. When Rosbach sold the company in 2012, it had elated 12 million dollars in annual sales and phenomenal growth. After his departure from Hydro Flask, he continued his world travel’s, become a practitioner of yoga and meditation, a paddleboarder and a business consultant, and a father (!). He has no regrets about selling the company; at the time, he was ready for a change and has created a fantastic life moving forward helping others create what they want.',
	],
];
